version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./vest:/vest
      - ./config/nginx:/etc/nginx/conf.d
      - ./vest/vest/static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: django
    command: bash -c "sleep 10 && python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn vest.wsgi -b 0.0.0.0:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./vest:/vest
      - ./vest/vest/static:/static
    expose:
      - "8000"

  db:
    restart: always
    image: mdillon/postgis:latest
    container_name: pgis
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:latest
