version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./vest:/vest
      - ./config/nginx:/etc/nginx/conf.d
      - ./vest/vest/static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: django
    # command: bash -c "sleep 10 && npm install && npm run build && python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && supervisord"
    command: bash -c "sleep 10 && python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && supervisord"
    depends_on:
      - db
    links:
      - redis
    volumes:
      - ./vest:/vest
    expose:
      - "80"

  db:
    restart: always
    image: mdillon/postgis:latest
    container_name: pgis
    expose:
      - "5432"

  redis:
    image: redis:latest
    expose:
      - "6379"
