# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20170312_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlocation',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
    ]
