# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateWeather',
            fields=[
                ('weather_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.Weather')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='users.VestUser')),
            ],
            bases=('weather.weather',),
        ),
        migrations.CreateModel(
            name='PublicWeather',
            fields=[
                ('weather_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weather.Weather')),
            ],
            bases=('weather.weather',),
        ),
    ]
