# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatrange',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Hot', 'Hot'), ('Eco', 'Eco'), ('Night', 'Night')], max_length=10),
        ),
        migrations.AlterField(
            model_name='heattypedefinition',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Hot', 'Hot'), ('Eco', 'Eco'), ('Night', 'Night')], max_length=10),
        ),
        migrations.AlterField(
            model_name='homedayschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
